// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class IWQ_MP
{
    public int MPId { get; set; }

    public int StId { get; set; }

    public string MPName { get; set; }

    public int DeptId { get; set; }

    public virtual IWQ_Dept Dept { get; set; }

    public virtual ICollection<IWQ_Record> IWQ_Records { get; set; } = new List<IWQ_Record>();

    public virtual IWQ_St St { get; set; }
}