// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class IWQ_Record
{
    public int RecordId { get; set; }

    public int? MPId { get; set; }

    public DateTime? SampleDate { get; set; }

    public decimal? Temp { get; set; }

    public decimal? PH { get; set; }

    public decimal? EC { get; set; }

    public string Note { get; set; }

    public virtual IWQ_MP MP { get; set; }
}