// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class IWQ_Dept
{
    public int DeptId { get; set; }

    public string DeptName { get; set; }

    public virtual ICollection<IWQ_MP> IWQ_MPs { get; set; } = new List<IWQ_MP>();

    public virtual ICollection<IWQ_St> IWQ_Sts { get; set; } = new List<IWQ_St>();
}