// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class IWQ_St
{
    public int StId { get; set; }

    public int DeptId { get; set; }

    public string StName { get; set; }

    public decimal? TWD97Lon { get; set; }

    public decimal? TWD97Lat { get; set; }

    public string SiteAddress { get; set; }

    public int? CountyId { get; set; }

    public int? TownId { get; set; }

    public virtual Ref_County County { get; set; }

    public virtual IWQ_Dept Dept { get; set; }

    public virtual ICollection<IWQ_MP> IWQ_MPs { get; set; } = new List<IWQ_MP>();

    public virtual Ref_Town Town { get; set; }
}