// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class Ref_River
{
    public int RiverId { get; set; }

    public string RiverName { get; set; }

    public string RiverEngName { get; set; }

    public string RiverCode { get; set; }

    public int? ParentId { get; set; }

    public string Description { get; set; }
}