// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class Ref_County
{
    public int CountyId { get; set; }

    public string CountyName { get; set; }

    public string CountyCode { get; set; }

    public int Sort { get; set; }

    public virtual ICollection<IWQ_St> IWQ_Sts { get; set; } = new List<IWQ_St>();

    public virtual ICollection<Ref_Town> Ref_Towns { get; set; } = new List<Ref_Town>();

    public virtual ICollection<UG_St> UG_Sts { get; set; } = new List<UG_St>();

    public virtual ICollection<WQ_St> WQ_Sts { get; set; } = new List<WQ_St>();
}