// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class Ref_Town
{
    public int TownId { get; set; }

    public string TownName { get; set; }

    public string TownCode { get; set; }

    public int CountyId { get; set; }

    public virtual Ref_County County { get; set; }

    public virtual ICollection<IWQ_St> IWQ_Sts { get; set; } = new List<IWQ_St>();

    public virtual ICollection<UG_St> UG_Sts { get; set; } = new List<UG_St>();

    public virtual ICollection<WQ_St> WQ_Sts { get; set; } = new List<WQ_St>();
}