// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class Ref_Basin
{
    public int BasinId { get; set; }

    public string BasinName { get; set; }

    public string BasinCode { get; set; }

    public virtual ICollection<WQ_St> WQ_Sts { get; set; } = new List<WQ_St>();
}