// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class UG_Item
{
    public int ItemId { get; set; }

    public int ItemCategoryId { get; set; }

    public string ItemName { get; set; }

    public string ItemEngName { get; set; }

    public string ItemEngabbreviation { get; set; }

    public string ItemUnit { get; set; }

    public virtual UG_ItemCategory ItemCategory { get; set; }

    public virtual ICollection<UG_Record> UG_Records { get; set; } = new List<UG_Record>();
}