// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class UG_Record
{
    public int RecordId { get; set; }

    public int? StId { get; set; }

    public int ItemId { get; set; }

    public string ItemValue { get; set; }

    public decimal? ItemValue_Num { get; set; }

    public DateTime SampleDate { get; set; }

    public string Note { get; set; }

    public virtual UG_Item Item { get; set; }

    public virtual UG_St St { get; set; }
}