// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class WQ_ItemCategory
{
    public int ItemCategoryId { get; set; }

    public string ItemCategoryName { get; set; }

    public string ItemCategoryEngName { get; set; }

    public int Sort { get; set; }

    public virtual ICollection<WQ_Item> WQ_Items { get; set; } = new List<WQ_Item>();
}