// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgHack.Models;

public partial class WQ_St
{
    public int StId { get; set; }

    public string SiteId { get; set; }

    public string SiteName { get; set; }

    public string SiteEngName { get; set; }

    public int? CountyId { get; set; }

    public int? TownId { get; set; }

    public int? BasinId { get; set; }

    public string River { get; set; }

    public decimal? TWD97Lon { get; set; }

    public decimal? TWD97Lat { get; set; }

    public decimal? TWD97TM2X { get; set; }

    public decimal? TWD97TM2Y { get; set; }

    public string SiteAddress { get; set; }

    public int StatusOfUse { get; set; }

    public virtual Ref_Basin Basin { get; set; }

    public virtual Ref_County County { get; set; }

    public virtual Ref_Town Town { get; set; }

    public virtual ICollection<WQ_Record> WQ_Records { get; set; } = new List<WQ_Record>();
}